
// Interpretações Astrológicas Avançadas
// Baseado no material: Guia de Pesquisa para Astrologia Avançada

export const PLANETS_IN_SIGNS: Record<string, Record<string, string>> = {
    "Sol": {
        "Áries": "Liderança, impulsividade, coragem, pioneirismo. Você se expressa através da ação direta e da conquista.",
        "Touro": "Estabilidade, persistência, sensualidade, materialismo. Você busca segurança e prazeres sensoriais duradouros.",
        "Gêmeos": "Curiosidade, comunicação, versatilidade, inquietude. Sua essência é mental, adaptável e sempre em busca de novidades.",
        "Câncer": "Sensibilidade, proteção, intuição, apego emocional. Você brilha ao cuidar e nutrir, valorizando raízes e sentimentos.",
        "Leão": "Brilho, criatividade, orgulho, generosidade. Você nasceu para ser visto, liderar e expressar sua individualidade com calor.",
        "Virgem": "Análise, perfeccionismo, utilidade, discrição. Sua essência busca a ordem, o serviço e o aprimoramento constante.",
        "Libra": "Diplomacia, equilíbrio, estética, indecisão. Você se realiza através das parcerias, da beleza e da harmonia social.",
        "Escorpião": "Intensidade, transformação, mistério, poder. Sua energia é profunda, regeneradora e busca a verdade oculta.",
        "Sagitário": "Otimismo, liberdade, filosofia, expansão. Você busca o sentido da vida, a aventura e a verdade superior.",
        "Capricórnio": "Ambição, disciplina, estrutura, reserva. Sua essência é voltada para a realização, o status e a construção sólida.",
        "Aquário": "Originalidade, humanitarismo, rebeldia, visão de futuro. Você brilha ao inovar e defender ideais coletivos.",
        "Peixes": "Empatia, espiritualidade, imaginação, sacrifício. Sua essência é compassiva, artística e conectada ao todo."
    },
    "Lua": {
        "Áries": "Reações rápidas, impaciência emocional, necessidade de independência. Você se sente seguro quando pode agir livremente.",
        "Touro": "Necessidade de segurança material, estabilidade emocional, teimosia. O conforto físico é essencial para seu bem-estar.",
        "Gêmeos": "Emoções racionais, necessidade de falar sobre sentimentos, dispersão. Você processa o que sente através da mente.",
        "Câncer": "Emoções profundas, forte instinto materno/protetor, mudanças de humor. A Lua está em casa aqui, sensível e acolhedora.",
        "Leão": "Necessidade de admiração, drama emocional, lealdade. Você expressa sentimentos com calor e teatralidade.",
        "Virgem": "Emoções analisadas, necessidade de ordem, preocupação excessiva. Você demonstra cuidado através de gestos práticos.",
        "Libra": "Necessidade de harmonia, busca de paz em relacionamentos, evitação de conflitos. Você precisa de beleza e parceria para estar bem.",
        "Escorpião": "Intensidade emocional extrema, ciúme, poder de regeneração. Suas emoções são águas profundas e transformadoras.",
        "Sagitário": "Necessidade de liberdade emocional, otimismo cego, busca de aventura. Você lida com sentimentos com humor e filosofia.",
        "Capricórnio": "Reserva emocional, seriedade, necessidade de controle. Você pode parecer frio, mas leva sentimentos e deveres muito a sério.",
        "Aquário": "Desapego emocional, necessidade de espaço, amizade acima do romance. Você racionaliza sentimentos e valoriza a liberdade.",
        "Peixes": "Hipersensibilidade, absorção de energias alheias, confusão emocional. Você sente o mundo e precisa de refúgio espiritual."
    },
    "Mercúrio": {
        "Áries": "Fala direta, mente rápida, competitividade intelectual. Pensamento decisivo e sem rodeios.",
        "Touro": "Pensamento prático, fala lenta e deliberada, teimosia mental. Mente focada em resultados tangíveis.",
        "Gêmeos": "Mente versátil, curiosidade extrema, habilidade multitarefa. Mercúrio em casa: inteligência ágil e comunicativa.",
        "Câncer": "Memória excelente, pensamento influenciado pela emoção, intuição. Mente fotográfica e imaginativa.",
        "Leão": "Expressão dramática, mente criativa, autoridade na fala. Pensamento focado na autoexpressão confiante.",
        "Virgem": "Precisão, mente crítica, foco em detalhes e organização. Mercúrio em domicílio: análise lógica impecável.",
        "Libra": "Diplomacia mental, busca de consenso, indecisão intelectual. Mente que pesa todos os lados antes de julgar.",
        "Escorpião": "Mente investigativa, sarcasmo, foco em segredos e profundidade. Pensamento detetive que vai à raiz.",
        "Sagitário": "Pensamento filosófico, visão ampla, tendência a exageros. Mente voltada para o abstrato e o futuro.",
        "Capricórnio": "Mente lógica, foco em resultados práticos, seriedade. Pensamento estruturado e ambicioso.",
        "Aquário": "Ideias inovadoras, pensamento original, desapego intelectual. Mente inventiva e progressista.",
        "Peixes": "Pensamento intuitivo, imaginação fértil, dificuldade com lógica pura. Mente poética e visual."
    },
    "Vênus": {
        "Áries": "Amor impulsivo, atração por desafios, independência afetiva. Conquista rápida e paixão ardente.",
        "Touro": "Amor estável e sensorial, valorização do conforto e posses. Vênus em casa: lealdade, toque e prazer.",
        "Gêmeos": "Atração intelectual, necessidade de variedade, flerte. Amor que precisa de conversa e estímulo mental.",
        "Câncer": "Amor protetor e sensível, busca de segurança familiar. Afeto maternal e cuidado profundo.",
        "Leão": "Amor generoso e dramático, necessidade de ser adorado. Lealdade real e gestos grandiosos.",
        "Virgem": "Amor prático e reservado, demonstração de afeto através do serviço. Relações baseadas na utilidade e pureza.",
        "Libra": "Amor romântico e estético, busca de equilíbrio e parceria. Vênus em casa: charme, beleza e justiça no amor.",
        "Escorpião": "Amor intenso e possessivo, busca de fusão total. Paixão transformadora, ciúme e profundidade.",
        "Sagitário": "Amor livre e aventureiro, atração por outras culturas. Relações baseadas em crescimento e liberdade.",
        "Capricórnio": "Amor sério e ambicioso, valorização de status e estabilidade. Afeto contido, mas duradouro e responsável.",
        "Aquário": "Amor amigável e independente, atração por originalidade. Relações livres de preconceitos e posse.",
        "Peixes": "Amor idealizado e compassivo, tendência ao sacrifício. Vênus exaltada: amor incondicional e romântico."
    },
    "Marte": {
        "Áries": "Ação imediata, competitividade nata, coragem física. Marte em casa: guerreiro nato, direto e assertivo.",
        "Touro": "Ação persistente e lenta, foco em resultados materiais. Força inabalável e paciência estratégica.",
        "Gêmeos": "Ação dispersa e versátil, energia gasta na comunicação. Luta com palavras e inteligência.",
        "Câncer": "Ação motivada pela emoção, proteção agressiva do lar. Guerreiro defensivo tenaz.",
        "Leão": "Ação criativa e dramática, desejo de liderança. Luta por honra, reconhecimento e autoexpressão.",
        "Virgem": "Ação organizada e técnica, foco em eficiência. Energia canalizada para o trabalho e perfeição.",
        "Libra": "Ação diplomática, dificuldade em agir sozinho. Luta pela justiça e busca aliados.",
        "Escorpião": "Ação estratégica e intensa, persistência implacável. Marte em domicílio: força oculta e regeneradora.",
        "Sagitário": "Ação entusiasmada e aventureira, busca de liberdade. Energia voltada para ideais e exploração.",
        "Capricórnio": "Ação disciplinada e ambiciosa, foco em longo prazo. Marte exaltado: construtor incansável.",
        "Aquário": "Ação original e humanitária, rebeldia contra o status quo. Luta pela liberdade e inovação.",
        "Peixes": "Ação intuitiva e sutil, energia flutuante. Luta por sonhos e ideais espirituais."
    },
    "Júpiter": {
        "Áries": "Sorte através da coragem e liderança pioneira.",
        "Touro": "Expansão através da estabilidade e recursos materiais tangíveis.",
        "Gêmeos": "Sorte através da comunicação, curiosidade e versatilidade.",
        "Câncer": "Expansão através da nutrição, família e proteção emocional.",
        "Leão": "Sorte através da criatividade, autoconfiança e brilho pessoal.",
        "Virgem": "Expansão através do serviço, detalhe e aperfeiçoamento técnico.",
        "Libra": "Sorte através de parcerias, diplomacia e senso estético.",
        "Escorpião": "Expansão através da transformação, profundidade e poder oculto.",
        "Sagitário": "O posicionamento mais forte; sorte em viagens, filosofia e fé.",
        "Capricórnio": "Expansão através da disciplina, estrutura sólida e ambição.",
        "Aquário": "Sorte através da inovação, originalidade e ideais sociais.",
        "Peixes": "Expansão através da espiritualidade, compaixão e artes."
    },
    "Saturno": {
        "Áries": "Desafio em liderar, necessidade de aprender paciência e controle da impulsividade.",
        "Touro": "Medo da escassez, necessidade de construir segurança material sólida.",
        "Gêmeos": "Medo de ser superficial, necessidade de estruturar o conhecimento e a fala.",
        "Câncer": "Bloqueios emocionais, necessidade de construir bases familiares seguras.",
        "Leão": "Medo de não ser reconhecido, necessidade de disciplinar a criatividade e o ego.",
        "Virgem": "Obsessão por detalhes, necessidade de aprender a delegar e servir com limites.",
        "Libra": "Desafios em parcerias, necessidade de aprender compromisso real e justiça.",
        "Escorpião": "Medo da vulnerabilidade, necessidade de estruturar o poder pessoal e sexual.",
        "Sagitário": "Ceticismo, necessidade de encontrar uma verdade estruturada e ética.",
        "Capricórnio": "O posicionamento natural; grande ambição, autoridade e senso de dever.",
        "Aquário": "Medo da exclusão social, necessidade de estruturar ideais e inovações.",
        "Peixes": "Medos vagos, necessidade de estruturar a espiritualidade e o caos emocional."
    },
    "Urano": {
        "Áries": "Revolução individualista, inovações súbitas na autoafirmação.",
        "Touro": "Mudanças na economia, valores materiais e relação com a terra.",
        "Gêmeos": "Novas formas de comunicação, pensamento rápido e disruptivo.",
        "Câncer": "Mudanças na estrutura familiar, libertação de padrões emocionais passados.",
        "Leão": "Revolução criativa, expressão única e libertação do ego.",
        "Virgem": "Inovações na saúde, trabalho, rotina e tecnologia aplicada.",
        "Libra": "Mudanças nos relacionamentos, leis sociais e conceitos de justiça.",
        "Escorpião": "Transformações radicais, descobertas ocultas e regeneração sexual.",
        "Sagitário": "Novas filosofias, liberdade de crença e formas de viajar.",
        "Capricórnio": "Mudanças nas estruturas de poder, governos e hierarquias.",
        "Aquário": "Inovações tecnológicas, sociais e humanitárias em larga escala.",
        "Peixes": "Revolução na espiritualidade, arte e inconsciente coletivo."
    },
    "Netuno": {
        "Áries": "Idealismo na ação, coragem inspirada e lutas espirituais.",
        "Touro": "Sonhos de estabilidade, paraíso material e beleza natural.",
        "Gêmeos": "Idealismo na comunicação, poesia e intuição mental.",
        "Câncer": "Sonhos de proteção, união familiar idealizada e sensibilidade.",
        "Leão": "Idealização da arte, romance de cinema e glamour.",
        "Virgem": "Sonhos de cura perfeita, serviço abnegado e pureza.",
        "Libra": "Idealização da paz, beleza, harmonia e parcerias perfeitas.",
        "Escorpião": "Sonhos de transformação profunda, mistério e fusão d'alma.",
        "Sagitário": "Idealismo filosófico, busca de utopias e fé universal.",
        "Capricórnio": "Sonhos de estrutura perfeita, sucesso social e ambição espiritualizada.",
        "Aquário": "Idealização da fraternidade, comunidades utópicas e futuro.",
        "Peixes": "Espiritualidade universal, dissolução do ego e amor incondicional."
    },
    "Plutão": {
        "Áries": "Transformação da identidade, coragem para renascer e força bruta.",
        "Touro": "Transformação dos valores, economia e relação com a natureza.",
        "Gêmeos": "Transformação da mente, comunicação e poder das ideias.",
        "Câncer": "Transformação na família, segurança emocional e raízes.",
        "Leão": "Transformação no poder individual, criatividade e liderança.",
        "Virgem": "Transformação na saúde, trabalho e purificação do sistema.",
        "Libra": "Transformação nos relacionamentos, justiça e equilíbrio de poder.",
        "Escorpião": "O posicionamento mais intenso; transformação total, morte e renascimento.",
        "Sagitário": "Transformação nas crenças, religião e busca da verdade.",
        "Capricórnio": "Transformação nas instituições, governos e estruturas sociais.",
        "Aquário": "Transformação no coletivo, tecnologia e evolução humana.",
        "Peixes": "Transformação na alma, inconsciente e dissolução final."
    }
};
